spring:
  application:
    name: client
  main:
    banner-mode: off
#
#  ssl:
#    bundle:
#      jks:
#        messageserver:
#          key:
#            alias: "messageserver"
#          keystore:
#            location: "classpath:messageserver-identity.p12"
#            password: "password"
#            type: "PKCS12"
#          truststore:
#            location: "classpath:messageserver-truststore.p12"
#            password: "password"
#            type: "PKCS12"

  ssl:
    bundle:
      jks:
        demo-client:
          key:
            alias: demo-client-sample
          keystore:
            location: classpath:client-keystore.p12
            password: password
            type: "PKCS12"


server:
  port: 8080
  address: 127.0.0.1
  ssl:
    enabled: false
    bundle: demo-client

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


app:
  auth:
    provider:
      spring:
        issuer-uri: 'http://localhost:9000'
      spring-tls:
        issuer-uri: 'https://localhost:9443'

messages:
  base-uri: http://127.0.0.1:8443/messages

logging:
  level:
    org.springframework.security: trace

