spring:
  application:
    name: client
  main:
    banner-mode: off
#
#  ssl:
#    bundle:
#      jks:
#        messageserver:
#          key:
#            alias: "messageserver"
#          keystore:
#            location: "classpath:messageserver-identity.p12"
#            password: "password"
#            type: "PKCS12"
#          truststore:
#            location: "classpath:messageserver-truststore.p12"
#            password: "password"
#            type: "PKCS12"
  security:
    oauth2:
      client:
        registration:
          messaging-client-oidc:
            provider: spring
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: 'http://127.0.0.1:8080/login/oauth2/code/{registrationId}'
            client-name: messaging-client-oidc
            scope:
              - profile
              - openid

          messaging-client-authorization-code:
            provider: spring
            client-name: messaging-client-authorization-code
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: 'http://127.0.0.1:8080/authorized'
            scope:
              - message.read
              - message.write

          mtls-demo-client-client-credentials:
            provider: spring-tls
            client-id: mtls-demo-client
            client-authentication-method: tls_client_auth
            authorization-grant-type: client_credentials
            scope: message.read,message.write
            client-name: mtls-demo-client-client-credentials

        provider:
          spring:
            issuer-uri: http://localhost:9000
          spring-tls:
            token-uri: https://localhost:9443/oauth2/token


  ssl:
    bundle:
      jks:
        demo-client:
          key:
            alias: demo-client-sample
          keystore:
            location: classpath:client-keystore.p12
            password: password
            type: "PKCS12"
          truststore:
            location: classpath:client-truststore.p12
            password: password
            type: "PKCS12"


server:
  port: 8080
  address: 127.0.0.1
  ssl:
    enabled: false
    bundle: demo-client

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


#app:
#  auth:
#    provider:
#      spring:
#        issuer-uri: 'http://localhost:9000'
#      spring-tls:
#        issuer-uri: 'https://localhost:9443'

messages:
  base-uri: https://127.0.0.1:8443/messages

logging:
  level:
    org.springframework.security: trace
    reactor.netty.http.client: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
    org.springframework.web.reactive.function.client.ExchangeFilterFunction: TRACE
    org.springframework.web.reactive.function.client.DefaultWebClient: TRACE

