spring:
  application:
    name: client
  main:
    banner-mode: off

server:
  port: 8080
  address: 127.0.0.1


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

messages:
  base-uri: http://127.0.0.1:8443/messages

logging:
  level:
    org.springframework.security: trace

