spring:
  application:
    name: message-resource

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
  ssl:
    bundle:
      jks:
        message-server:
          key:
            alias: resource-server
          keystore:
            location: "classpath:resource-server.p12"
            password: "password"
            type: "PKCS12"
          truststore:
            location: classpath:client-truststore.p12
            password: password
            type: PKCS12






server:
  port: 8443
  ssl:
    enabled: true
    client-auth: need
    bundle: message-server
#  ssl:
#    bundle: messageserver
#    client-auth: need
#    enabled: false





logging:
  level:
    org.springframework.security: trace
    org.springframework.security.oauth2: trace
