spring:
  application:
    name: oauth2
  main:
    banner-mode: off

  ssl:
    bundle:
      jks:
        demo-authorizationserver:
          key:
            alias: demo-authorizationserver-sample
            password: password
          keystore:
            location: classpath:keystore.p12
            password: password
            type: PKCS12
          truststore:
            location: classpath:keystore.p12
            password: password
            type: PKCS12


server:
  port: 9443
  ssl:
    bundle: demo-authorizationserver
    client-auth: want

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


logging:
  level:
    org.springframework.security: trace

