spring:
  application:
    name: oauth2
  main:
    banner-mode: off

  ssl:
    bundle:
      jks:
        ca-signed-client:
          truststore:
            location: classpath:truststore.p12
            password: changeit
            type: PKCS12
          keystore:
            location: classpath:server-keystore.p12
            password: password
            type: PKCS12



server:
  port: 9443
  ssl:
    enabled: true
#    key-store: classpath:server-keystore.p12
#    key-store-password: password  # or the password you gave
#    key-store-type: PKCS12
#
#    trust-store: classpath:truststore.p12
#    trust-store-password: changeit  # or your password
#    trust-store-type: PKCS12
    client-auth: want
    bundle: ca-signed-client

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


logging:
  level:
    org.springframework.security: trace

